- set_fact:
    tmp_dir: "{{ tmp_prefix }}/{{ product }}/{{ product }}-{{ product_version }}"
    product_name: "{{ urls[product][product_version].tarball.name }}"
    product_start: "{{ urls[product][product_version].tarball.start }}"
    product_image: "{{ urls[product][product_version].tarball.image }}"
    product_home: "{{ prefix }}/{{ product }}/{{ urls[product][product_version].tarball.dir }}"
    product_url: "{{ urls[product][product_version].tarball.url }}"
    product_hash: "{{ urls[product][product_version].tarball.hash }}"
- set_fact:
    product_file: "{{ tmp_dir }}/{{ urls[product][product_version].tarball.file }}"

- name: "Create Directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ tmp_dir }}"
    - "{{ product_home }}"

- name: "Download {{ product }}"
  get_url:
    url: "{{ product_url }}"
    dest: "{{ product_file }}"
    checksum: "sha256:{{ product_hash }}"


- name: Extract product
  unarchive:
    src: "{{ product_file }}"
    dest: "{{ prefix }}/{{ product }}"
    remote_src: yes

- template: 
    src: "product.sh.j2"
    dest: "/etc/profile.d/{{ product }}.sh"
    mode: 0644

- template:
    src: "product.desktop.j2"
    dest: "/usr/local/share/applications/{{ product }}.desktop"
    mode: 0644

- name: Clean Temporary files
  file: 
    path: "{{ tmp_dir }}"
    state: absent

- name: "Fix Permissions"
  shell: "{{ item }}"
  args:
    chdir: "{{ prefix }}"
  with_items:
    - "chown -R root:root ."
    - "find . -perm -u+r -exec chmod a+r {} \\;"
    - "find . -perm -u+w -exec chmod a+w {} \\;"
    - "find . -perm -u+x -exec chmod a+x {} \\;"

